name: i-am-testing
favicon: null
layout_spectrum: 0.5874143312685192
typography_spectrum: 0.7672650087624788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2635544228833169
  lightness: 0.05951289599761367
  saturation: 0.48651804658584297
  rhythmicContrast: 0.03630409063771367
purpose: []
